version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=event_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_HOST=db
        DB_PORT=5432
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  database:
