# Generated by Django 5.0.8 on 2024-08-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='area_uid',
            field=models.CharField(blank=True, help_text='The area uid where the event was captured from', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='zone_uid',
            field=models.CharField(blank=True, help_text='The zone uid where the event was captured from', max_length=200, null=True),
        ),
    ]
